// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package models

import (
	"database/sql"
	"time"
)

type Card struct {
	ID          int64
	Name        string
	Description string
	UserID      int64
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
	RemovedAt   sql.NullTime
}

type Comment struct {
	ID        int64
	Content   string
	CardID    int64
	UserID    int64
	CommentID sql.NullInt64
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	RemovedAt sql.NullTime
}

type Downvote struct {
	ID        int64
	CardID    int64
	UserID    int64
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	RemovedAt sql.NullTime
}

type Upvote struct {
	ID        int64
	CardID    int64
	UserID    int64
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	RemovedAt sql.NullTime
}

type User struct {
	ID         int64
	Name       string
	Email      string
	Username   string
	Password   string
	UserTypeID int64
	CreatedAt  time.Time
	UpdatedAt  sql.NullTime
	RemovedAt  sql.NullTime
}

type UserType struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	RemovedAt sql.NullTime
}
